language: go
sudo: false

env:
  global:
    - GO111MODULE=on
    - DEPLOY_WITH_MAJOR="1.11"

before_script:
  - go vet ./...

go:
  - "1.11.x"

script: go test -race -v ./...

deploy:
  provider: script
  script: etc/travis-deploy.sh
  on:
    tags: true
    branch: master
